/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacessssss;
//import com.mycompany.p2tarea3grupo2.interfaceone.Events;

import com.mycompany.p2tarea3grupo2.classe.Event;
import com.mycompany.p2tarea3grupo2.interfaces.admin.InitAdmi;
import com.mycompany.p2tarea3grupo2.interfaces.admin.ModificarAdmi;
import com.mycompany.p2tarea3grupo2.interfaces.admin.RegistroAdmi;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import java.awt.Color;
//import java.awt.Event;
import javax.swing.border.MatteBorder;

/**
 *
 * @author User
 */
public class Administrador extends javax.swing.JFrame {
    Event event;

    
    private int initX, initY;
    
    public Administrador() {
        initComponents();
        event = new Event();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlActions = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblTitleApp = new javax.swing.JLabel();
        panelPerfilAdmi = new javax.swing.JPanel();
        panelContent = new javax.swing.JPanel();
        panelWallpaper = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlActions.setBackground(new java.awt.Color(243, 243, 243));
        pnlActions.setBorder(new MatteBorder(1,1,1,1,new Color(204,204,204)));
        pnlActions.setPreferredSize(new java.awt.Dimension(1200, 20));
        pnlActions.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlActionsMouseDragged(evt);
            }
        });
        pnlActions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlActionsMouseEntered(evt);
            }
        });

        lblExit.setBackground(new java.awt.Color(243, 243, 243));
        lblExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("X");
        lblExit.setOpaque(true);
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });

        lblMinimize.setBackground(new java.awt.Color(243, 243, 243));
        lblMinimize.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimize.setText("-");
        lblMinimize.setToolTipText("");
        lblMinimize.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblMinimize.setOpaque(true);
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseExited(evt);
            }
        });

        lblTitleApp.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblTitleApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/IconEspe.png"))); // NOI18N
        lblTitleApp.setText(" Universidad de las fuerzas Armadas ESPE");

        javax.swing.GroupLayout pnlActionsLayout = new javax.swing.GroupLayout(pnlActions);
        pnlActions.setLayout(pnlActionsLayout);
        pnlActionsLayout.setHorizontalGroup(
            pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlActionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleApp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 860, Short.MAX_VALUE)
                .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlActionsLayout.setVerticalGroup(
            pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActionsLayout.createSequentialGroup()
                .addGroup(pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblTitleApp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblExit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMinimize, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlActions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 20));

        panelPerfilAdmi.setOpaque(false);
        panelPerfilAdmi.setPreferredSize(new java.awt.Dimension(1200, 610));

        panelContent.setOpaque(false);
        panelContent.setPreferredSize(new java.awt.Dimension(990, 350));

        javax.swing.GroupLayout panelContentLayout = new javax.swing.GroupLayout(panelContent);
        panelContent.setLayout(panelContentLayout);
        panelContentLayout.setHorizontalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
        );
        panelContentLayout.setVerticalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelPerfilAdmiLayout = new javax.swing.GroupLayout(panelPerfilAdmi);
        panelPerfilAdmi.setLayout(panelPerfilAdmiLayout);
        panelPerfilAdmiLayout.setHorizontalGroup(
            panelPerfilAdmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerfilAdmiLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(panelContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        panelPerfilAdmiLayout.setVerticalGroup(
            panelPerfilAdmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerfilAdmiLayout.createSequentialGroup()
                .addContainerGap(220, Short.MAX_VALUE)
                .addComponent(panelContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        getContentPane().add(panelPerfilAdmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        panelWallpaper.setPreferredSize(new java.awt.Dimension(1200, 610));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/FondoAdimistrador.png"))); // NOI18N

        javax.swing.GroupLayout panelWallpaperLayout = new javax.swing.GroupLayout(panelWallpaper);
        panelWallpaper.setLayout(panelWallpaperLayout);
        panelWallpaperLayout.setHorizontalGroup(
            panelWallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWallpaperLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelWallpaperLayout.setVerticalGroup(
            panelWallpaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWallpaperLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(panelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1200, 610));

        panelPrincipal.setPreferredSize(new java.awt.Dimension(1200, 630));

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        getContentPane().add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        lblExit.setBackground(Color.red);
        lblExit.setForeground(Color.white);
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        lblExit.setForeground(Color.black);
        lblExit.setBackground(new Color(243,243,243));
    }//GEN-LAST:event_lblExitMouseExited

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        this.setExtendedState(1);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseEntered
        lblMinimize.setBackground(new Color(230,230,230));
    }//GEN-LAST:event_lblMinimizeMouseEntered

    private void lblMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseExited
        lblMinimize.setBackground(new Color(243,243,243));
    }//GEN-LAST:event_lblMinimizeMouseExited

    private void pnlActionsMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlActionsMouseDragged
        int newX  = getLocation().x + evt.getX() - initX;
        int newY = getLocation().y + evt.getY() - initY;

        this.setLocation(newX, newY);
    }//GEN-LAST:event_pnlActionsMouseDragged

    private void pnlActionsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlActionsMouseEntered
        initX = evt.getX();
        initY = evt.getY();
    }//GEN-LAST:event_pnlActionsMouseEntered

     private void showPanel(JPanel p){
        p.setSize(990, 350);
        p.setLocation(0, 0);
        
        panelContent.removeAll();
        panelContent.add(p,BorderLayout.CENTER);
        panelContent.revalidate();
        panelContent.repaint();
    }
     
    
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblTitleApp;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelPerfilAdmi;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelWallpaper;
    private javax.swing.JPanel pnlActions;
    // End of variables declaration//GEN-END:variables
}
