/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.p2tarea3grupo2.interfaces.admin;

/**
 *
 * @author User
 */
public class InitAdmi extends javax.swing.JPanel {

    /**
     * Creates new form InitAdmi
     */
    public InitAdmi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelInicio2 = new ComponentRoundJilmar.PanelRound();
        lblPerfilAdministrativo = new javax.swing.JLabel();
        lblImagenAjustes = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelInicio2.setBackground(new java.awt.Color(204, 204, 204));
        PanelInicio2.setRoundBottomLeft(50);
        PanelInicio2.setRoundBottomRight(50);
        PanelInicio2.setRoundTopLeft(50);
        PanelInicio2.setRoundTopRight(50);

        lblPerfilAdministrativo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPerfilAdministrativo.setForeground(new java.awt.Color(51, 51, 51));
        lblPerfilAdministrativo.setText("Perfil Administrativo");

        lblImagenAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/AjustesInicioAdmi.png"))); // NOI18N

        javax.swing.GroupLayout PanelInicio2Layout = new javax.swing.GroupLayout(PanelInicio2);
        PanelInicio2.setLayout(PanelInicio2Layout);
        PanelInicio2Layout.setHorizontalGroup(
            PanelInicio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInicio2Layout.createSequentialGroup()
                .addGroup(PanelInicio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelInicio2Layout.createSequentialGroup()
                        .addGap(413, 413, 413)
                        .addComponent(lblPerfilAdministrativo))
                    .addGroup(PanelInicio2Layout.createSequentialGroup()
                        .addGap(464, 464, 464)
                        .addComponent(lblImagenAjustes)))
                .addContainerGap(417, Short.MAX_VALUE))
        );
        PanelInicio2Layout.setVerticalGroup(
            PanelInicio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInicio2Layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(lblImagenAjustes)
                .addGap(18, 18, 18)
                .addComponent(lblPerfilAdministrativo)
                .addGap(149, 149, 149))
        );

        add(PanelInicio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ComponentRoundJilmar.PanelRound PanelInicio2;
    private javax.swing.JLabel lblImagenAjustes;
    private javax.swing.JLabel lblPerfilAdministrativo;
    // End of variables declaration//GEN-END:variables
}
