/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.p2tarea3grupo2.interfaces.admin;

import java.awt.Color;

public class ModificarAdmi extends javax.swing.JPanel {

    /**
     * Creates new form ModificarAdmi
     */
    public ModificarAdmi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelModificar = new ComponentRoundJilmar.PanelRound();
        panelDatosInstitucionalesMod = new ComponentRoundJilmar.PanelRound();
        lblTituloID1 = new javax.swing.JLabel();
        lblIDMod = new javax.swing.JLabel();
        lblTituloCorreoMod = new javax.swing.JLabel();
        lblCorreoEspeMod = new javax.swing.JLabel();
        lblTituloContraseñaMod = new javax.swing.JLabel();
        lblContraseñaMod = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTituloNM = new javax.swing.JLabel();
        lblTituloAM = new javax.swing.JLabel();
        lblTituloCM = new javax.swing.JLabel();
        lblTituloGM = new javax.swing.JLabel();
        lblTituloDM = new javax.swing.JLabel();
        lblTituloTM = new javax.swing.JLabel();
        panelDireccionMod = new ComponentRoundJilmar.PanelRound();
        txtDireccionMod = new javax.swing.JTextField();
        panelCedulaMod = new ComponentRoundJilmar.PanelRound();
        txtCedulaMod = new javax.swing.JTextField();
        panelApellidosMod = new ComponentRoundJilmar.PanelRound();
        txtApellidosMod = new javax.swing.JTextField();
        panelTelefonoMod = new ComponentRoundJilmar.PanelRound();
        txtTelefonoMod = new javax.swing.JTextField();
        lblTituloTSM = new javax.swing.JLabel();
        lblTituloFNM = new javax.swing.JLabel();
        lblTituloCPM = new javax.swing.JLabel();
        lblTituloNAM = new javax.swing.JLabel();
        lblTituloC = new javax.swing.JLabel();
        lblTituloN = new javax.swing.JLabel();
        panelNombreMod = new ComponentRoundJilmar.PanelRound();
        txtNombresMod = new javax.swing.JTextField();
        lblCarreraMod = new javax.swing.JLabel();
        lblNivelMod = new javax.swing.JLabel();
        panelCorreoPersonalMod = new ComponentRoundJilmar.PanelRound();
        txtCorreoPersonalMod = new javax.swing.JTextField();
        panelNacionalidadMod = new ComponentRoundJilmar.PanelRound();
        txtNacionalidadMod = new javax.swing.JTextField();
        panelGeneroMod = new ComponentRoundJilmar.PanelRound();
        txtGeneroMod = new javax.swing.JTextField();
        panelFechaNacimiento = new ComponentRoundJilmar.PanelRound();
        txtFechaNacimientoMod = new javax.swing.JTextField();
        panelTipoSangreMod = new ComponentRoundJilmar.PanelRound();
        txtTipoSangreMod = new javax.swing.JTextField();
        panelBusqueda = new ComponentRoundJilmar.PanelRound();
        txtBusqueda = new javax.swing.JTextField();
        lblBuscar = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelModificar.setBackground(new java.awt.Color(204, 204, 204));
        PanelModificar.setMaximumSize(new java.awt.Dimension(940, 340));
        PanelModificar.setPreferredSize(new java.awt.Dimension(990, 350));
        PanelModificar.setRoundBottomLeft(50);
        PanelModificar.setRoundBottomRight(50);
        PanelModificar.setRoundTopLeft(50);
        PanelModificar.setRoundTopRight(50);

        panelDatosInstitucionalesMod.setBackground(new java.awt.Color(102, 0, 0));
        panelDatosInstitucionalesMod.setRoundBottomLeft(33);
        panelDatosInstitucionalesMod.setRoundBottomRight(33);
        panelDatosInstitucionalesMod.setRoundTopLeft(33);
        panelDatosInstitucionalesMod.setRoundTopRight(33);

        lblTituloID1.setForeground(new java.awt.Color(255, 255, 204));
        lblTituloID1.setText("ID");

        lblIDMod.setForeground(new java.awt.Color(255, 255, 204));
        lblIDMod.setText("L00456878");

        lblTituloCorreoMod.setForeground(new java.awt.Color(255, 255, 204));
        lblTituloCorreoMod.setText("Correo Institucional");

        lblCorreoEspeMod.setForeground(new java.awt.Color(255, 255, 204));
        lblCorreoEspeMod.setText("dlbautista5.edu.ec");

        lblTituloContraseñaMod.setForeground(new java.awt.Color(255, 255, 204));
        lblTituloContraseñaMod.setText("Contraseña");

        lblContraseñaMod.setForeground(new java.awt.Color(255, 255, 204));
        lblContraseñaMod.setText("150207");

        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("jLabel3");

        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setText("jLabel4");

        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("jLabel5");

        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout panelDatosInstitucionalesModLayout = new javax.swing.GroupLayout(panelDatosInstitucionalesMod);
        panelDatosInstitucionalesMod.setLayout(panelDatosInstitucionalesModLayout);
        panelDatosInstitucionalesModLayout.setHorizontalGroup(
            panelDatosInstitucionalesModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosInstitucionalesModLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosInstitucionalesModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosInstitucionalesModLayout.createSequentialGroup()
                        .addGroup(panelDatosInstitucionalesModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDatosInstitucionalesModLayout.createSequentialGroup()
                                .addComponent(lblTituloID1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblIDMod, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosInstitucionalesModLayout.createSequentialGroup()
                                .addGroup(panelDatosInstitucionalesModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTituloContraseñaMod, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTituloCorreoMod))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelDatosInstitucionalesModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblContraseñaMod)
                                    .addComponent(lblCorreoEspeMod, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(panelDatosInstitucionalesModLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(102, 102, 102))
                    .addGroup(panelDatosInstitucionalesModLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(102, 102, 102))))
        );
        panelDatosInstitucionalesModLayout.setVerticalGroup(
            panelDatosInstitucionalesModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosInstitucionalesModLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelDatosInstitucionalesModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloID1)
                    .addComponent(lblIDMod))
                .addGap(18, 18, 18)
                .addGroup(panelDatosInstitucionalesModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloCorreoMod)
                    .addComponent(lblCorreoEspeMod))
                .addGap(18, 18, 18)
                .addGroup(panelDatosInstitucionalesModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloContraseñaMod)
                    .addComponent(lblContraseñaMod))
                .addGap(18, 18, 18)
                .addGroup(panelDatosInstitucionalesModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(panelDatosInstitucionalesModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        lblTituloNM.setText("Nombres");

        lblTituloAM.setText("Apellidos");

        lblTituloCM.setText("Cedula");

        lblTituloGM.setText("Genero");

        lblTituloDM.setText("Direccion");

        lblTituloTM.setText("Tlf Personal");

        panelDireccionMod.setBackground(new java.awt.Color(255, 255, 255));
        panelDireccionMod.setRoundBottomLeft(33);
        panelDireccionMod.setRoundBottomRight(33);
        panelDireccionMod.setRoundTopLeft(33);
        panelDireccionMod.setRoundTopRight(33);

        txtDireccionMod.setBorder(null);

        javax.swing.GroupLayout panelDireccionModLayout = new javax.swing.GroupLayout(panelDireccionMod);
        panelDireccionMod.setLayout(panelDireccionModLayout);
        panelDireccionModLayout.setHorizontalGroup(
            panelDireccionModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDireccionModLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(txtDireccionMod, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDireccionModLayout.setVerticalGroup(
            panelDireccionModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtDireccionMod, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        panelCedulaMod.setBackground(new java.awt.Color(255, 255, 255));
        panelCedulaMod.setRoundBottomLeft(33);
        panelCedulaMod.setRoundBottomRight(33);
        panelCedulaMod.setRoundTopLeft(33);
        panelCedulaMod.setRoundTopRight(33);

        txtCedulaMod.setBorder(null);

        javax.swing.GroupLayout panelCedulaModLayout = new javax.swing.GroupLayout(panelCedulaMod);
        panelCedulaMod.setLayout(panelCedulaModLayout);
        panelCedulaModLayout.setHorizontalGroup(
            panelCedulaModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCedulaModLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtCedulaMod, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCedulaModLayout.setVerticalGroup(
            panelCedulaModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCedulaMod, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        panelApellidosMod.setBackground(new java.awt.Color(255, 255, 255));
        panelApellidosMod.setRoundBottomLeft(33);
        panelApellidosMod.setRoundBottomRight(33);
        panelApellidosMod.setRoundTopLeft(33);
        panelApellidosMod.setRoundTopRight(33);

        txtApellidosMod.setBorder(null);

        javax.swing.GroupLayout panelApellidosModLayout = new javax.swing.GroupLayout(panelApellidosMod);
        panelApellidosMod.setLayout(panelApellidosModLayout);
        panelApellidosModLayout.setHorizontalGroup(
            panelApellidosModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelApellidosModLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(txtApellidosMod, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelApellidosModLayout.setVerticalGroup(
            panelApellidosModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtApellidosMod, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        panelTelefonoMod.setBackground(new java.awt.Color(255, 255, 255));
        panelTelefonoMod.setRoundBottomLeft(33);
        panelTelefonoMod.setRoundBottomRight(33);
        panelTelefonoMod.setRoundTopLeft(33);
        panelTelefonoMod.setRoundTopRight(33);

        txtTelefonoMod.setBorder(null);

        javax.swing.GroupLayout panelTelefonoModLayout = new javax.swing.GroupLayout(panelTelefonoMod);
        panelTelefonoMod.setLayout(panelTelefonoModLayout);
        panelTelefonoModLayout.setHorizontalGroup(
            panelTelefonoModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTelefonoModLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(txtTelefonoMod, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelTelefonoModLayout.setVerticalGroup(
            panelTelefonoModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTelefonoMod, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        lblTituloTSM.setText("Tipo Sanguineo");

        lblTituloFNM.setText("Fecha de Nacimiento");

        lblTituloCPM.setText("Correo Personal");

        lblTituloNAM.setText("Nacionalidad");

        lblTituloC.setText("Carrera");

        lblTituloN.setText("Nivel");

        panelNombreMod.setBackground(new java.awt.Color(255, 255, 255));
        panelNombreMod.setRoundBottomLeft(33);
        panelNombreMod.setRoundBottomRight(33);
        panelNombreMod.setRoundTopLeft(33);
        panelNombreMod.setRoundTopRight(33);

        txtNombresMod.setBorder(null);

        javax.swing.GroupLayout panelNombreModLayout = new javax.swing.GroupLayout(panelNombreMod);
        panelNombreMod.setLayout(panelNombreModLayout);
        panelNombreModLayout.setHorizontalGroup(
            panelNombreModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNombreModLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(txtNombresMod, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panelNombreModLayout.setVerticalGroup(
            panelNombreModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNombresMod, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        lblCarreraMod.setText("Tecnologías de la Información ");

        lblNivelMod.setText("Primer Nivel");

        panelCorreoPersonalMod.setBackground(new java.awt.Color(255, 255, 255));
        panelCorreoPersonalMod.setRoundBottomLeft(33);
        panelCorreoPersonalMod.setRoundBottomRight(33);
        panelCorreoPersonalMod.setRoundTopLeft(33);
        panelCorreoPersonalMod.setRoundTopRight(33);

        txtCorreoPersonalMod.setBorder(null);

        javax.swing.GroupLayout panelCorreoPersonalModLayout = new javax.swing.GroupLayout(panelCorreoPersonalMod);
        panelCorreoPersonalMod.setLayout(panelCorreoPersonalModLayout);
        panelCorreoPersonalModLayout.setHorizontalGroup(
            panelCorreoPersonalModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCorreoPersonalModLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtCorreoPersonalMod, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelCorreoPersonalModLayout.setVerticalGroup(
            panelCorreoPersonalModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCorreoPersonalModLayout.createSequentialGroup()
                .addComponent(txtCorreoPersonalMod)
                .addGap(12, 12, 12))
        );

        panelNacionalidadMod.setBackground(new java.awt.Color(255, 255, 255));
        panelNacionalidadMod.setRoundBottomLeft(33);
        panelNacionalidadMod.setRoundBottomRight(33);
        panelNacionalidadMod.setRoundTopLeft(33);
        panelNacionalidadMod.setRoundTopRight(33);

        txtNacionalidadMod.setBorder(null);

        javax.swing.GroupLayout panelNacionalidadModLayout = new javax.swing.GroupLayout(panelNacionalidadMod);
        panelNacionalidadMod.setLayout(panelNacionalidadModLayout);
        panelNacionalidadModLayout.setHorizontalGroup(
            panelNacionalidadModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNacionalidadModLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtNacionalidadMod, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panelNacionalidadModLayout.setVerticalGroup(
            panelNacionalidadModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNacionalidadMod, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        panelGeneroMod.setBackground(new java.awt.Color(255, 255, 255));
        panelGeneroMod.setRoundBottomLeft(33);
        panelGeneroMod.setRoundBottomRight(33);
        panelGeneroMod.setRoundTopLeft(33);
        panelGeneroMod.setRoundTopRight(33);

        txtGeneroMod.setBorder(null);

        javax.swing.GroupLayout panelGeneroModLayout = new javax.swing.GroupLayout(panelGeneroMod);
        panelGeneroMod.setLayout(panelGeneroModLayout);
        panelGeneroModLayout.setHorizontalGroup(
            panelGeneroModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneroModLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtGeneroMod, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGeneroModLayout.setVerticalGroup(
            panelGeneroModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtGeneroMod, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        panelFechaNacimiento.setBackground(new java.awt.Color(255, 255, 255));
        panelFechaNacimiento.setRoundBottomLeft(33);
        panelFechaNacimiento.setRoundBottomRight(33);
        panelFechaNacimiento.setRoundTopLeft(33);
        panelFechaNacimiento.setRoundTopRight(33);

        txtFechaNacimientoMod.setBorder(null);

        javax.swing.GroupLayout panelFechaNacimientoLayout = new javax.swing.GroupLayout(panelFechaNacimiento);
        panelFechaNacimiento.setLayout(panelFechaNacimientoLayout);
        panelFechaNacimientoLayout.setHorizontalGroup(
            panelFechaNacimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechaNacimientoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtFechaNacimientoMod, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelFechaNacimientoLayout.setVerticalGroup(
            panelFechaNacimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtFechaNacimientoMod, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        panelTipoSangreMod.setBackground(new java.awt.Color(255, 255, 255));
        panelTipoSangreMod.setRoundBottomLeft(33);
        panelTipoSangreMod.setRoundBottomRight(33);
        panelTipoSangreMod.setRoundTopLeft(33);
        panelTipoSangreMod.setRoundTopRight(33);

        txtTipoSangreMod.setBorder(null);

        javax.swing.GroupLayout panelTipoSangreModLayout = new javax.swing.GroupLayout(panelTipoSangreMod);
        panelTipoSangreMod.setLayout(panelTipoSangreModLayout);
        panelTipoSangreModLayout.setHorizontalGroup(
            panelTipoSangreModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoSangreModLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtTipoSangreMod, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelTipoSangreModLayout.setVerticalGroup(
            panelTipoSangreModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTipoSangreMod, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        panelBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        panelBusqueda.setRoundBottomLeft(33);
        panelBusqueda.setRoundBottomRight(33);
        panelBusqueda.setRoundTopLeft(33);
        panelBusqueda.setRoundTopRight(33);

        txtBusqueda.setBorder(null);

        lblBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LupaBusqueda.png"))); // NOI18N

        javax.swing.GroupLayout panelBusquedaLayout = new javax.swing.GroupLayout(panelBusqueda);
        panelBusqueda.setLayout(panelBusquedaLayout);
        panelBusquedaLayout.setHorizontalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelBusquedaLayout.setVerticalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 0));
        jLabel11.setText("Búsqueda");

        javax.swing.GroupLayout PanelModificarLayout = new javax.swing.GroupLayout(PanelModificar);
        PanelModificar.setLayout(PanelModificarLayout);
        PanelModificarLayout.setHorizontalGroup(
            PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelModificarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloDM)
                    .addComponent(lblTituloAM)
                    .addComponent(lblTituloCM)
                    .addComponent(lblTituloNM)
                    .addComponent(lblTituloGM)
                    .addComponent(jLabel11)
                    .addComponent(lblTituloTM))
                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelModificarLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelModificarLayout.createSequentialGroup()
                                .addComponent(panelTelefonoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(lblTituloN))
                            .addGroup(PanelModificarLayout.createSequentialGroup()
                                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(panelDireccionMod, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(panelCedulaMod, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(panelApellidosMod, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(panelNombreMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panelGeneroMod, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(32, 32, 32)
                                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelModificarLayout.createSequentialGroup()
                                        .addComponent(lblTituloCPM)
                                        .addGap(40, 40, 40)
                                        .addComponent(panelCorreoPersonalMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelModificarLayout.createSequentialGroup()
                                        .addComponent(lblTituloC)
                                        .addGap(86, 86, 86)
                                        .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNivelMod)
                                            .addComponent(lblCarreraMod)))
                                    .addGroup(PanelModificarLayout.createSequentialGroup()
                                        .addComponent(lblTituloNAM)
                                        .addGap(54, 54, 54)
                                        .addComponent(panelNacionalidadMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(PanelModificarLayout.createSequentialGroup()
                                .addGap(265, 265, 265)
                                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTituloFNM)
                                    .addComponent(lblTituloTSM))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panelTipoSangreMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelModificarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(panelDatosInstitucionalesMod, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        PanelModificarLayout.setVerticalGroup(
            PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelModificarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelModificarLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelModificarLayout.createSequentialGroup()
                        .addComponent(panelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloNM)
                    .addComponent(panelNombreMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTipoSangreMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituloTSM))
                .addGap(22, 22, 22)
                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloFNM)
                    .addComponent(panelApellidosMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituloAM)
                    .addComponent(panelFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelModificarLayout.createSequentialGroup()
                        .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelCedulaMod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTituloCM, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelModificarLayout.createSequentialGroup()
                        .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTituloCPM)
                            .addComponent(panelCorreoPersonalMod, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelModificarLayout.createSequentialGroup()
                        .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTituloGM)
                            .addComponent(panelGeneroMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTituloNAM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelModificarLayout.createSequentialGroup()
                                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelDireccionMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTituloDM)
                                    .addGroup(PanelModificarLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(lblCarreraMod)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTituloTM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(PanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblTituloN)
                                            .addComponent(lblNivelMod))
                                        .addComponent(panelTelefonoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lblTituloC))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelModificarLayout.createSequentialGroup()
                        .addComponent(panelNacionalidadMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelModificarLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(panelDatosInstitucionalesMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        add(PanelModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ComponentRoundJilmar.PanelRound PanelModificar;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCarreraMod;
    private javax.swing.JLabel lblContraseñaMod;
    private javax.swing.JLabel lblCorreoEspeMod;
    private javax.swing.JLabel lblIDMod;
    private javax.swing.JLabel lblNivelMod;
    private javax.swing.JLabel lblTituloAM;
    private javax.swing.JLabel lblTituloC;
    private javax.swing.JLabel lblTituloCM;
    private javax.swing.JLabel lblTituloCPM;
    private javax.swing.JLabel lblTituloContraseñaMod;
    private javax.swing.JLabel lblTituloCorreoMod;
    private javax.swing.JLabel lblTituloDM;
    private javax.swing.JLabel lblTituloFNM;
    private javax.swing.JLabel lblTituloGM;
    private javax.swing.JLabel lblTituloID1;
    private javax.swing.JLabel lblTituloN;
    private javax.swing.JLabel lblTituloNAM;
    private javax.swing.JLabel lblTituloNM;
    private javax.swing.JLabel lblTituloTM;
    private javax.swing.JLabel lblTituloTSM;
    private ComponentRoundJilmar.PanelRound panelApellidosMod;
    private ComponentRoundJilmar.PanelRound panelBusqueda;
    private ComponentRoundJilmar.PanelRound panelCedulaMod;
    private ComponentRoundJilmar.PanelRound panelCorreoPersonalMod;
    private ComponentRoundJilmar.PanelRound panelDatosInstitucionalesMod;
    private ComponentRoundJilmar.PanelRound panelDireccionMod;
    private ComponentRoundJilmar.PanelRound panelFechaNacimiento;
    private ComponentRoundJilmar.PanelRound panelGeneroMod;
    private ComponentRoundJilmar.PanelRound panelNacionalidadMod;
    private ComponentRoundJilmar.PanelRound panelNombreMod;
    private ComponentRoundJilmar.PanelRound panelTelefonoMod;
    private ComponentRoundJilmar.PanelRound panelTipoSangreMod;
    private javax.swing.JTextField txtApellidosMod;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtCedulaMod;
    private javax.swing.JTextField txtCorreoPersonalMod;
    private javax.swing.JTextField txtDireccionMod;
    private javax.swing.JTextField txtFechaNacimientoMod;
    private javax.swing.JTextField txtGeneroMod;
    private javax.swing.JTextField txtNacionalidadMod;
    private javax.swing.JTextField txtNombresMod;
    private javax.swing.JTextField txtTelefonoMod;
    private javax.swing.JTextField txtTipoSangreMod;
    // End of variables declaration//GEN-END:variables
}
