/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.p2tarea3grupo2.interfaces.admin;

import com.mycompany.p2tarea3grupo2.classe.Event;
import java.awt.Color;
import javax.swing.JOptionPane;

public class RegistroAdmi extends javax.swing.JPanel {
        Event event;


    /**
     * Creates new form RegistroAdmi
     */
    public RegistroAdmi() {
        initComponents();
        botones.add(RadioButtonProfesor);
        botones.add(RadioButtonEstudiante);
        event = new Event();

       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botones = new javax.swing.ButtonGroup();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    }// </editor-fold>//GEN-END:initComponents

    private void labelRoundRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRoundRegistrarMouseClicked
        // TODO add your handling code here:
        /*if(RadioButtonProfesor.isSelected()){
            
        }else if(RadioButtonEstudiante.isSelected()){
            
        }*/
        
    }//GEN-LAST:event_labelRoundRegistrarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup botones;
    // End of variables declaration//GEN-END:variables
}
/*   

Validacion de correo electronico

public boolean validacionEmail(){
Pattern patron = Pattern.compile();

Matcher mat = patron.matcher(correo);
return mat.find("([a-z0-9]+ {\\.?[a-z0-9])*)+@);


}


*/