/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package repasoexamenpoo.view;

import javax.swing.JOptionPane;
import org.bson.Document;
import repasoexamenpoo.operaciones.Actualizar;
import repasoexamenpoo.operaciones.Busqueda;
import repasoexamenpoo.operaciones.Cliente;

/**
 *
 * @author EFRAIN
 */
public class Banco extends javax.swing.JFrame {
    Actualizar act;
    Busqueda bs;
    Cliente clientLoco; //Local
    Cliente client; //Destinatario
    Document docLoco;
    Document docClient;

    /**
     * Creates new form Banco
     */
    public Banco() {
        act = new Actualizar();
        bs = new Busqueda();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtNroCuenta = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        txtDestinatario = new javax.swing.JTextField();
        lbSaldoDispo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnTransferir = new javax.swing.JButton();
        btnBuscarLocal = new javax.swing.JButton();
        btnBuscarDestinatario = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        txtTipoC = new javax.swing.JTextField();
        lbSaldoDispo1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNroDesti = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Banco ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 29, -1, -1));

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 107, -1, -1));

        jLabel3.setText("Nro de Cuenta");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 171, -1, -1));

        jLabel4.setText("Monto");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel5.setText("Tipo de Cuenta");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel6.setText("Destinatario");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 193, -1));

        txtNroCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNroCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNroCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 196, -1));
        getContentPane().add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 196, -1));
        getContentPane().add(txtDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 193, -1));

        lbSaldoDispo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbSaldoDispo.setText("$ ");
        getContentPane().add(lbSaldoDispo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        jLabel8.setText("Saldo Disponible");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, 20));

        btnTransferir.setText("Trasferir");
        btnTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferirActionPerformed(evt);
            }
        });
        getContentPane().add(btnTransferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 140, -1));

        btnBuscarLocal.setText("Buscar Local");
        btnBuscarLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarLocalActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 140, -1));

        btnBuscarDestinatario.setText("Buscar Destinatario");
        btnBuscarDestinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDestinatarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 140, -1));

        btnRegistrar.setText("Registrar");
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 140, -1));
        getContentPane().add(txtTipoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 190, -1));

        lbSaldoDispo1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbSaldoDispo1.setText("00.0");
        getContentPane().add(lbSaldoDispo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, -1));

        jLabel7.setText("Nro Cuenta Destinatario");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));
        getContentPane().add(txtNroDesti, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirActionPerformed
        // TODO add your handling code here:
        trans();
    }//GEN-LAST:event_btnTransferirActionPerformed

    private void btnBuscarLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLocalActionPerformed
        // TODO add your handling code here:
        busqueda();
        
    }//GEN-LAST:event_btnBuscarLocalActionPerformed

    private void txtNroCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNroCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNroCuentaActionPerformed

    private void btnBuscarDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDestinatarioActionPerformed
        // TODO add your handling code here:
        busqueda2();
    }//GEN-LAST:event_btnBuscarDestinatarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Banco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarDestinatario;
    private javax.swing.JButton btnBuscarLocal;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnTransferir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbSaldoDispo;
    private javax.swing.JLabel lbSaldoDispo1;
    private javax.swing.JTextField txtDestinatario;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNroCuenta;
    private javax.swing.JTextField txtNroDesti;
    private javax.swing.JTextField txtTipoC;
    // End of variables declaration//GEN-END:variables

public void busqueda(){
    
    String nombre = txtNombre.getText();
    
    clientLoco = bs.getClient(nombre);
    
    if(clientLoco == null){
        JOptionPane.showMessageDialog(null, "El usuario no se encontro");
    return ;    
    }
    
    txtNroCuenta.setText(String.valueOf(clientLoco.getNumCuenta()));
    txtTipoC.setText(clientLoco.getTipoCuenta());
    lbSaldoDispo1.setText(String.valueOf(clientLoco.getSaldo()));
    
    docLoco = clientLoco.DevuelveDoc(clientLoco);
}

public void busqueda2(){
    
    String nombre = txtDestinatario.getText();
    
    client = bs.getClient(nombre);
    
    if(client == null){
        JOptionPane.showMessageDialog(null, "El usuario no se encontro");
    return ;    
    }
    
    txtNroDesti.setText(String.valueOf(client.getNumCuenta()));
    
    docClient = client.DevuelveDoc(client);
}

    private void trans() {
        
        double saldoActual = clientLoco.getSaldo();
        double monto = Double.parseDouble(txtMonto.getText());
        
        ///Destinaterio
        double SaldoDestinatario = client.getSaldo();
        //Restar el saldo de la cuenta actual
        
        double total = saldoActual - monto;
        System.out.println("Total: "+total);
        Cliente clientnuevo = clientLoco;
        clientnuevo.setSaldo(total);
        Document doc = clientnuevo.DevuelveDoc(clientnuevo);
        System.out.println(doc.toJson());
        act.ActualizarMongo(docLoco, doc);

        
        //Suma de plata transferida en la cuenta del desinaterio
        double TotalTrasferido = SaldoDestinatario + monto;
        
        Cliente client2 = client;
        client2.setSaldo(TotalTrasferido);
        Document doc2 = client2.DevuelveDoc(client2);
        System.out.println(doc2.toJson());
        
        act.ActualizarMongo(docClient, doc2);
        lbSaldoDispo1.setText(String.valueOf(clientnuevo.getSaldo()));

        
    }


}

